#!/bin/bash

set -e

get_path() {
  if [ -L $1 ]; then
    readlink -f $1
  else
    echo $1
  fi
}

SCRIPT_PATH=$(get_path $0)
SCRIPT_DIR=$(cd $(dirname $SCRIPT_PATH) && pwd)
SCRIPT_NAME=$(basename $SCRIPT_PATH)
SYS_ROOT=$(cd $SCRIPT_DIR && rustc --print sysroot)
LD_LIBRARY_PATH=$SYS_ROOT/lib $SCRIPT_DIR/target/release/$SCRIPT_NAME $@
